### ISSUE TITLE
about odom

### ISSUE THREAD

**Issue by Npang-WXY** [rock-slam/slam-odometry#2]
Hi, is the odom calculation based on a four-wheeled, all-way, all-drive robot model?

**Comment by jmachowinski** [comment]
There are multiple models implemented.
Which one are you referring to ?

**Comment by Npang-WXY** [comment]
Thanks for your reply, we have four hub motors as drive motors and have another four motors as steering motors, do you understand what I mean?

**Comment by jmachowinski** [comment]
Please look into the headers of the implemented odometry models and read the documentation.
Also note, that this code is part of a bigger robotics framework and is hard to be used independent.
